# Generated by Django 2.2 on 2019-04-12 21:06

from django.db import migrations, models
import django.db.models.deletion
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('First_Name', models.CharField(max_length=30)),
                ('Middle_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('City', models.CharField(default='Chandigarh', max_length=30)),
                ('State', models.CharField(default='Chandigarh', max_length=30)),
                ('Student_ID', management.models.IntegerRangeField(primary_key=True, serialize=False)),
                ('Phone_Number', management.models.IntegerRangeField()),
                ('Date_of_Birth', models.DateField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Course_Number', management.models.IntegerRangeField()),
                ('Course_Credits', management.models.IntegerRangeField(default=4)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Department')),
            ],
        ),
    ]
