# Generated by Django 2.2 on 2019-04-14 20:22

from django.db import migrations, models
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_course_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='Semester',
            field=management.models.IntegerRangeField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='Year',
            field=management.models.IntegerRangeField(default=1),
        ),
    ]
