# Generated by Django 2.2 on 2019-04-14 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20190414_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Programme',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.Programme'),
        ),
    ]
