# Generated by Django 2.2 on 2019-04-14 23:49

from django.db import migrations, models
import django.db.models.deletion
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_student_programme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Faculty_ID', management.models.IntegerRangeField(primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=30)),
                ('Middle_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Phone_Number', management.models.IntegerRangeField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Course')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Department')),
            ],
        ),
    ]
