# Generated by Django 2.2 on 2019-04-14 23:59

from django.db import migrations
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Semester',
            field=management.models.IntegerRangeField(default=1),
        ),
    ]
