# Generated by Django 2.2 on 2019-04-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_course_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('L', 'Lecture Hall'), ('T', 'Tutorial Room')], default='L', max_length=1)),
                ('Number', models.CharField(max_length=2)),
            ],
        ),
    ]
