# Generated by Django 2.2 on 2019-04-15 01:08

from django.db import migrations, models
import django.db.models.deletion
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='id',
        ),
        migrations.AddField(
            model_name='venue',
            name='Department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='management.Department'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='Number',
            field=management.models.IntegerRangeField(primary_key=True, serialize=False),
        ),
    ]
