# Generated by Django 2.2 on 2019-04-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20190415_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Designation',
            field=models.CharField(choices=[('Prof.', 'Professor'), ('Dr.', 'Doctor'), ('Ass. Prof.', 'Associate Professor')], default='Prof.', max_length=15),
        ),
    ]
